### ISSUE TITLE
Indexers never expire LIVE snapshots

### ISSUE THREAD

**Issue by bryanlb** [slackhq/kaldb#611]
### Describe the bug

Indexers currently never expire live snapshots. For long running indexers, this can cause disk saturation issues and also causes failures to delete once these reach the snapshot deletion service time.

```
Starting delete of snapshot SnapshotMetadata{name='LIVE_log_1689833167_dc25ce42-abbf-41ca-955e-e0888a66fe75', snapshotPath='LIVE', snapshotId='LIVE_log_1689833167_dc25ce42-abbf-41ca-955e-e0888a66fe75', startTimeEpochMs=1689228850484, endTimeEpochMs=1689837644041, maxOffset=45729812334, partitionId='83', indexType=LOGS_LUCENE9}
```
```
Exception deleting snapshot
error_root_cause_stack_trace:
    java.lang.IllegalArgumentException: Parameter 'Bucket' must not be null at software.amazon.awssdk.protocols.xml.internal.marshall.SimpleTypePathMarshaller.lambda$static$0(SimpleTypePathMarshaller.java:46) at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller.doMarshall(XmlProtocolMarshaller.java:104) at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller.marshall(XmlProtocolMarshaller.java:80) at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller.marshall(XmlProtocolMarshaller.java:49) at software.amazon.awssdk.services.s3.transform.ListObjectsV2RequestMarshaller.marshall(ListObjectsV2RequestMarshaller.java:51) at software.amazon.awssdk.services.s3.transform.Li
```

### To Reproduce
Long running indexers will show high stale snapshot counts on reboots. Also an increase in exception attempting to delete LIVE snapshots.

```
Deleting 38 stale snapshots: [SnapshotMetadata{name='LIVE_log_1690035728_cf55...
```

### Expected behavior
Indexers should expire LIVE snapshots after a configurable time, or once cache node(s) start serving the content.

**Comment by vthacker** [comment]
this fixes the symptom - https://github.com/slackhq/kaldb/pull/650

Probably not going to go with this

**Comment by bryanlb** [comment]
@kyle-sammons was digging on this today, and after we discussed his findings it appears that we do delete the chunks using the ChunkCleanerService (for indexers - not recovery). However, it appears that we may not be deleting the snapshots from ZK.

We should check to see if we leave the ZK nodes around - maybe also what happens when we have a ZK node that is searched but then doesn't exist on a node - why didn't that throw an exception? Or did it and we just didn't notice?

If the recovery nodes delete their chunks immediately after indexing in the RecoveryChunkManager indexer we may want to reconsider using a ChunkCleanerService here at all, and move this into the IndexingChunkManager for consistency.

In general, we should audit the recovery and indexer nodes - ensure both are cleaning up the disk appropriately, as well as ZK. And likely simplify some of the existing logic as it's currently a bit obtuse as to who cleans up what, when.
